services:
    nginx:
        image: nginx:latest
        container_name: web
        restart: unless-stopped
        ports:
            - '80:80'
        networks:
            dmz:
                ipv4_address: 10.0.0.3

networks:
    dmz:
        name: dmz
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
                  gateway: 10.0.0.1
